
export const FIND_CART_REQUEST = "FIND_CART_REQUEST";
export const FIND_CART_SUCCESS = "FIND_CART_SUCCESS";
export const FIND_CART_FAILURE = "FIND_CART_FAILURE";

export const ADD_ITEM_TO_CART_REQUEST = "ADD_ITEM_TO_CART_REQUEST";
export const ADD_ITEM_TO_CART_SUCCESS = "ADD_ITEM_TO_CART_SUCCESS";
export const ADD_ITEM_TO_CART_FAILURE = "ADD_ITEM_TO_CART_FAILURE";

export const DELETE_CART_ITEM_REQUEST = "DELETE_CART_ITEM_REQUEST";
export const DELETE_CART_ITEM_SUCCESS = "DELETE_CART_ITEM_SUCCESS";
export const DELETE_CART_ITEM_FAILURE = "DELETE_CART_ITEM_FAILURE";

export const UPDATE_CART_ITEM_QUANTITY_REQUEST = "UPDATE_CART_ITEM_QUANTITY_REQUEST";
export const UPDATE_CART_ITEM_QUANTITY_SUCCESS = "UPDATE_CART_ITEM_QUANTITY_SUCCESS";
export const UPDATE_CART_ITEM_QUANTITY_FAILURE = "UPDATE_CART_ITEM_QUANTITY_FAILURE";

export const CLEAR_CART_REQUEST = "CLEAR_CART_REQUEST";
export const CLEAR_CART_SUCCESS = "CLEAR_CART_SUCCESS";
export const CLEAR_CART_FAILURE = "CLEAR_CART_FAILURE";

export const GET_ALL_CART_ITEM_REQUEST = "GET_ALL_CART_ITEM_REQUEST";
export const GET_ALL_CART_ITEM_SUCCESS = "GET_ALL_CART_ITEM_SUCCESS";
export const GET_ALL_CART_ITEM_FAILURE = "GET_ALL_CART_ITEM_FAILURE";